### ISSUE TITLE
About Photo Orientation

### ISSUE THREAD

**Issue by kctong529** [cathaysia/digikamflowplugin#4]
I just started using this little plugin that comes with digiKam 7.6.0 (macOS 64-bits). I like this layout very much. Thanks for your work. However, some of my photos (in fact, about half of them) are portrait, while the layout seems to show all photos as landscape. I wonder if this is something I could configure with the "Custom Loader" option. Interestingly, after rotating a photo, the layout could display it as portrait. It crashes quite seriously when I tried to rotate and turn on FlowPlugin SlideShow in between.

**Comment by kctong529** [comment]
It seems that I was wrong in saying that "the layout show all photos as landscape". It doesn't. Some of them are displayed correctly, but just a few. I've looked at the EXIF information more closely, and found the "Orientation" are inconsistent. When it is "top, left", the layout would display it correctly. But other than that, there are also "right, top" and "left, bottom" which would fail this layout. There must be a simple way out.

**Comment by cathaysia** [comment]
That is, there are two bugs:

- some pictures not be loaded
- the Orientation metadata of pictures is be ignored.

For bug 2, I had push a commit to fix it. You can compile this plugin by yourself or switch to "Digikam Loader" to fix this.

For bug 1. After all pictures be loaded, please try to resize plugin's window, it is a bug truely, but I has not fix it this time.

**Comment by cathaysia** [comment]
I create some pictures and modify it's Orientation property by exiftool, it has eight values:

```
// https://www.exiftool.org/TagNames/EXIF.html
Horizontal (normal)
Mirror horizontal
Rotate 180
Mirror vertical
Mirror horizontal and rotate 270 CW
Rotate 90 CW
Mirror horizontal and rotate 90 CW
Rotate 270 CW
```

Here is the preview:
![图片](https://user-images.githubusercontent.com/42114817/158002547-92351b01-b402-4dd4-95b4-8b2bfb90126a.png)

![图片](https://user-images.githubusercontent.com/42114817/158002506-c4f80da3-d831-4550-9c09-018f4770f72e.png)

**Comment by cathaysia** [comment]
close
